### ISSUE TITLE
CANT INSTALL fish10: mirc.ini file could not be located.

### ISSUE THREAD

**Issue by sboulianne** [flakes/mirc_fish_10#39]
I just downloaded the latest installer and when I ran it:
Step 1: http://imgur.com/eYZxOBc
Error: http://imgur.com/Vuldmvb

We cant install fish10 with a non-standard path... Why ?

Thanks for your time and support!

**Comment by sboulianne** [comment]
I confirm with .zip file, it works like a charm.
The installer seem broken.

**Comment by Tmp341** [comment]
mirc.ini file is located in %appdata%\mIRC folder.

**Comment by sboulianne** [comment]
So, the installer is buggy and need to be fixed.
Why the installer ask us for the mirc.ini path if we cant specify it ?

Most people dont run mIRC on a standard path then we need to be able to change the mIRC.ini path.

Sincerely.

**Comment by flakes** [comment]
The installer checks for mIRC in:

a) Given path
b) %appdata%\mIRC\mirc.ini

The error message will also appear if your mirc.ini is stored in appdata but still contains portable=1 (which does not make much sense). Maybe this is the case on your setup?

**Comment by sboulianne** [comment]
Hi sir,
My mirc.ini is'nt appear in my %appdata%\mIRC\.
My mirc.ini is in my D:\mIRC... like all my configs file for mIRC.

**Comment by flakes** [comment]
Then maybe your mirc.ini does *not* contain `portable=yes` but is still located in the same folder as mirc.exe. Is that possible?

**Comment by sboulianne** [comment]
in mt mirc.ini, I have:
[about]
portable=no

My mirc.ini is located in the same folder as mirc.exe.

**Comment by flakes** [comment]
Can you type `/fishdebug` and copy/paste the first 5 sections (up to and including *Variables*)?

**Comment by sboulianne** [comment]
sorry for the delay.
before I created the ticket, I installed the module using the .zip file.
Do you want me to run it anyways ?
Here you go:
---------FISH DEBUG---------


::VERSION
mIRC version: 7.38
SSL version: 1.0.1.11
SSL ready: $true
SSL mode: 1


::mIRC
mIRC dir: D:\mIRC\
mIRC.exe: D:\mIRC\mirc.exe
mIRC.ini: D:\mIRC\mirc.ini
Portable: no


::Files
fish_10.dll: "D:\mIRC\fish_10.dll" - $true
fish_inject.dll: "D:\mIRC\fish_inject.dll" - $true
blow.ini: D:\mIRC\blow.ini - $true


::md5
fish_10.dll: 65c6a07f7ba1c55e4b13803b4a1356b2
fish_inject.dll: be99a8ce8767c0db0075cdff2fe4c2a6
fish_10.mrc: 3e9d4f8bfe665cbf7173c42587f89b9d


::Variables
blow_ini: D:\mIRC\blow.ini
FiSH_dll: "D:\mIRC\fish_10.dll"

**Comment by sboulianne** [comment]
Im available if you want to test something.
Just let me know.

**Comment by flakes** [comment]
Thanks for the info, I was not aware that mIRC is able to work this way. I will reproduce on my machine and fix the installer accordingly.

**Comment by flakes** [comment]
Fixed with commit 673101f6a011e2659d487f917b1a984623fba70f, the next release will have the updated installer.

Thanks for reporting!

**Comment by sboulianne** [comment]
It was a pleasure Flakes! ;)
Glad to know it helped the community!
