### ISSUE TITLE
Key length not enforced

### ISSUE THREAD

**Issue by emsquared** [flakes/mirc_fish_10#44]
The [code that is used for the ECB mode of operation](https://github.com/flakes/mirc_fish_10/blob/master/fish_10/src/blowfish.cpp) does not honor the 56 byte (448 bit) maximum key length [defined by the standard](https://en.wikipedia.org/wiki/Blowfish_(cipher)#The_algorithm).

An application that truncates its key is unable to decrypt data output by mIRC FiSH 10 when the mIRC user configured a key that exceeds this length.

Edit: corrected incorrect bit length in message

**Comment by flakes** [comment]
good catch. will look into it.

**Comment by flakes** [comment]
Fixed for the next release, thx again!

**Comment by emsquared** [comment]
Thank you for fixing this
