### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by zer0c0nf** [flakes/mirc_fish_10#46]
Hello,

Can you update with latest openssl version, 1.1.0?

Thx. ;-)

**Comment by flakes** [comment]
Not so easy this time, OpenSSL changed the DLL names as well as some APIs. Let's wait & see what Khaled does... OpenSSL 1.0.2h is still secure.

**Comment by zer0c0nf** [comment]
OpenSSL 1.0.2j is now available, including a security fix

https://www.openssl.org/news/secadv/20160926.txt

**Comment by flakes** [comment]
Updated to 1.0.2k!
