### ISSUE TITLE
hash for mirc_fish_10-with-ssl-2017-02-25.zip does not seem to match HASHES

### ISSUE THREAD

**Issue by silv3rr** [flakes/mirc_fish_10#48]
```
$ sha3sum mirc_fish_10-with-ssl-2017-02-25.zip
cbcfa6e4c3175d7e62d230d3fef72d54b8ffab05d42b516aa466c2af  mirc_fish_10-with-ssl-2017-02-25.zip
```
```
$ rhash -v --sha3-224 mirc_fish_10-with-ssl-2017-02-25.zip
Config file: /etc/rhashrc
Format string is: %{sha3224}  %p\n
cbcfa6e4c3175d7e62d230d3fef72d54b8ffab05d42b516aa466c2af  mirc_fish_10-with-ssl-2017-02-25.zip
```
tried downloading the file multiple times, from different connections

**Comment by silv3rr** [comment]
same for the setup.exe btw:

<pre>
$ sha3sum mirc_fish_10-setup-2017-02-25.exe 
91296ec254aa7b123eb467666d8697825e98159f845c78fc72b86512  ../mirc_fish_10-setup-2017-02-25.exe

$ rhash -v --sha3-224 mirc_fish_10-setup-2017-02-25.exe
Config file: /etc/rhashrc
Format string is: %{sha3224}  %p\n
91296ec254aa7b123eb467666d8697825e98159f845c78fc72b86512  mirc_fish_10-setup-2017-02-25.exe
</pre>

the md5/sha1 hashes do match

**Comment by flakes** [comment]
Thanks for noticing, must have been a mistake on our side. With the new release, hashes are ok.
