### ISSUE TITLE
Installer error "mirc.ini file could not be located" if %APPDATA%\mirc.ini is used

### ISSUE THREAD

**Issue by silv3rr** [flakes/mirc_fish_10#49]
1) Using mirc_fish_10-setup-2017-02-25.exe to update
2) Enter your path to mirc.exe here: "C:\Program Files (x86)\mIRC"
3) After clicking Next I get a Setup popup: ```mirc.ini file could not be located```

\- mirc.exe + ssl/fish10 dll's and mrc are in: ```C:\Program Files (x86)\mIRC```
\- mirc.ini + blow.ini are in: ```C:\Users\silver\AppData\Roaming\mIRC```
\- afaik these paths are used for the default way mIRC is installed nowadays.
\- no portable flag set
\- fish10 works fine with manual install from .zip 

<pre>
<---------FISH DEBUG---------
::VERSION
mIRC version: 7.47
SSL version: 1.0.2.8
SSL ready: $true
SSL mode: 1

::mIRC
mIRC dir: C:\Users\silver\AppData\Roaming\mIRC\
mIRC.exe: C:\Program Files (x86)\mIRC\mirc.exe
mIRC.ini: C:\Users\silver\AppData\Roaming\mIRC\mirc.ini
Portable: NotFound

::Files
fish_10.dll: "C:\Program Files (x86)\mIRC\fish_10.dll" - $true
version string: *** FiSH 10.2 *** by [c&f]  *** fish_10.dll     compiled Jun 15 2016 19:30:54 ***
fish_inject.dll: "C:\Program Files (x86)\mIRC\fish_inject.dll" - $true
version string: *** FiSH 10.2 *** by [c&f]  *** fish_inject.dll compiled Jun 15 2016 19:30:54 ***
blow.ini: C:\Users\silver\AppData\Roaming\mIRC\blow.ini - $true

::md5
fish_10.dll: 268adba46ec203edf1447b7549a9bbc7
fish_inject.dll: 8417d27881af45164667fe617aa52895
fish_10.mrc: dd6d5147cb2080cc6b71980039efc1f4

::Variables
blow_ini: C:\Users\silver\AppData\Roaming\mIRC\blow.ini
FiSH_dll: "C:\Program Files (x86)\mIRC\fish_10.dll"
</pre>

**Comment by flakes** [comment]
Can you please check if a `portable` setting exists in your mirc.ini and if it does, which value it is set to?

**Comment by silv3rr** [comment]
As I stated in the initial comment: no portable setting at all. Also says so in the debug output.
Just to make sure I just checked again:
```
C:\Users\silver\AppData\Roaming\mIRC>findstr /I portable mirc.ini && echo match || echo no match
no match
```

**Comment by flakes** [comment]
This behaviour is actually ok - if no portable setting exists, "yes" is assumed for legacy reasons.
