### ISSUE TITLE
not working anymore with mirc 7.49

### ISSUE THREAD

**Issue by silv3rr** [flakes/mirc_fish_10#51]
Seems fish10 stops working for mirc 7.49. Everything loads up fine without errors, dll's are loaded and `/fishdebug` looks ok, the hello world/blow.ini check at the end too. Keys are also loaded (`FiSH.showkey`), key exchange works. But messages/topics are not decrypted.

Switching back to the 7.48 mirc.exe solved the problem.
Using openssl 1.0.2k.

**Comment by d14m0nd0** [comment]
I confirm this as well. mirc_fish_10-with-ssl-2017-02-25.zip/exe works fine on mIRC v7.48, but stops on v7.49 that came out recently.

**Comment by 1337username** [comment]
Confirmed!

**Comment by Erroneuz** [comment]
Can confirm. Tried resetting, tried new blow.ini, nothing works. Something is broke with v7.49

/fishdebug decrypts HelloWorld correctly, but messages are not decrypted.

**Comment by ninrr** [comment]
Confirmed to not be working with mirc 7.49. I came online today to post this issue; I couldn't figure it out so went back to v7.48.

**Comment by n0rc** [comment]
Confirmed with mIRC v7.49, same issue: key exchange works, key is set correctly, outgoing messages are correctly encrypted but incoming messages are not decrypted.

**Comment by flakes** [comment]
Fixed, new release is available.
