### ISSUE TITLE
mIRC has Blowfish.  This script needs modernization.

### ISSUE THREAD

**Issue by a-raccoon** [flakes/mirc_fish_10#54]
mIRC currently integrates blowfish support via openssl and no longer requires external dll resources.  This script can be rewritten and modernized.  Support was added to the $encode() and $decode() functions with CBC and EBC modes, salt and iv capability.

**Comment by flakes** [comment]
Hi,

thank you for the information. However, that is out of scope in this project for two reasons:

1) Noone from our crew knows mIRC script at all, and personally I find it quite ugly. Feel free to fork this one or start your own project ;)

2) FiSH encryption is not at all state-of-the-art. It should be replaced with something solid (like OTR).
