### ISSUE TITLE
mIRC 7.53 - outgoing chat is displayed twice

### ISSUE THREAD

**Issue by owah** [flakes/mirc_fish_10#55]
I updated to mIRC 7.53 yesterday and since then every line I send, is displayed twice in my client. Once the way I am used to, and once with the arrow as well as asterisks. This happens in a query as well as in a regular channel.

```
[13:44:47] *** FiSH: Sent my DH1080 public key to participant, waiting for reply ...
[13:44:47] *** FiSH: Key for participant set to *censored*
[13:44:53] <me>· something something message 1
[13:44:53] -> *participant* something something message 1
[13:45:25] <me>· something something message 2
[13:45:25] -> *participant* something something message 2
[13:45:27] <me>· :-|
[13:45:27] -> *participant* :-|
[14:02:28] <participant> ~sarcastic response~
```

**Comment by gh0stface1** [comment]
whatever the crypt mark is set to prefix or suffix, you get the message twice as shown before

**Comment by BBen1979** [comment]
Samething here, Upgraded from a older version 7.xx to 7.55 and the issue started.

Setting crypt mark prefix,suffix,disabled didn't change anything.

It's annoying as hell. :)

I turned off fish_10.mrc and it work fine. 

Thanks for all the work Flakes btw!

**Comment by ShareScene** [comment]
We need a proper working version of blowfish for mirc 7.55 because this version fix a critical secure issue present in all versions

**Comment by Tachdelan** [comment]
in fish_10.mrc line 74, you can comment out the line that says "privmsg $target $1-" with ;# so the line looks like this:
;#privmsg $target $1-
That will remove the extra line when you have crypt-mark on outgoing messages.

**Comment by flakes** [comment]
Looks like it's a mrc script issue, we probably need some flag or something. Unfortunately, I have not been able to find the correct flag... therefore all I can do at this point is recommending to turn off outgoing crypt marks for now...

**Comment by flakes** [comment]
Responsible code is this: https://github.com/flakes/mirc_fish_10/blob/master/fish_10.mrc#L36

**Comment by silv3rr** [comment]
replace
https://github.com/flakes/mirc_fish_10/blob/8b61aaf4dbea5ae5825f1e56dc03cca6bebbd716/fish_10.mrc#L74
with smth like:
```
    if ($target ischan) { msg $target $1- }
    else { privmsg $target $1- }
    halt
```

**Comment by flakes** [comment]
The fix has been incorporated into the new version. Thanks!
