### ISSUE TITLE
Mirc 7.56 - FiSH will no longer load

### ISSUE THREAD

**Issue by 100DeadPixels** [flakes/mirc_fish_10#57]
When Mirc is started I just get the error "FiSH needs the OpenSSL DLLs to be installed and loaded"

The DDLs are present and FiSH will load fine again if I downgrade to 7.55. I have double checked all settings/files and I'm fairly sure its an issue related to 7.56.

**Comment by thezoggy** [comment]
I can confirm. FiSH has been working fine for awhile and after each upgrade. But now is borked on 7.56, most likely due to openssl update
> Updated libraries OpenSSL to v1.1.1b, LibZip to v1.5.2, and PCRE to v8.43.

**Comment by Freetekno** [comment]
Same issue. mirc 7.56

**Comment by dngpower** [comment]
same problem. with mirc 7.56

**Comment by EHCanadian** [comment]
Also confirmed.
https://www.mirc.com/whatsnew.txt

4.Updated OpenSSL library to v1.1.1b. Required code changes due to to
  changes in OpenSSL 1.1.x. Older OpenSSL versions are no longer
  supported. Compiled to work on XP. Dynamic loading of OpenSSL DLLs
  still supported as libcrypto-1_1.dll and libssl-1_1.dll.

**Comment by Shadow322** [comment]
fix when?

**Comment by thezoggy** [comment]
mirc 7.57 is out now with another openssl update:
> Updated OpenSSL library to v1.1.1c.

**Comment by itchykill** [comment]
Still an issue with mirc 7.57.

**Comment by graphixillusion** [comment]
I can confirm the issue with 7.57. Is this script going to be updated? Thank you!

**Comment by Shadow322** [comment]
Nope

**Comment by thezoggy** [comment]
few weeks back there was a new build in the irc channel that works with 7.57. just have patience

**Comment by Shadow322** [comment]
Link?

**Comment by thezoggy** [comment]
#fish_10 on efnet

**Comment by Shadow322** [comment]
Why lie?

**Comment by itchykill** [comment]
@Shadow322 It's at #fish10 on EFnet. Don't think there's a working edition yet, sadly.

**Comment by flakes** [comment]
Hello folks, sorry about not looking into this earlier. We are going to investigate this weekend :)

**Comment by flakes** [comment]
New version is out, have fun. Please open new tickets for feedback.
