### ISSUE TITLE
fish_inject.dll causing issues with anti-vira software

### ISSUE THREAD

**Issue by Erroneuz** [flakes/mirc_fish_10#62]
Just a headsup that several anti-vira software doesn't like the latest version of fish_inject.dll, including Windows Defender, which is built into Windows 10.

https://www.virustotal.com/gui/file/37112cf24dc1d4a05e275b8b852ecac7cb05e2e5915d2092a876cef6a825ca5e/detection

Manually allowing the file in AV software will naturally solve the problem.

**Comment by Shadow322** [comment]
yea what is the AV software actually detecting in the code and can it be fixed?

**Comment by flakes** [comment]
Note to me: revert https://github.com/flakes/mirc_fish_10/commit/cb63913d1e34c03c9bbe6b667a6b541eb52eaf06

**Comment by flakes** [comment]
Actually the more recent version of minhook causes less detections (only 5 now), not much more we can do about it. Let me know how it goes for you after the next release..
