### ISSUE TITLE
ERROR: key length exceeds limit of 56 bytes.

### ISSUE THREAD

**Issue by deepblue2000** [flakes/mirc_fish_10#63]
hello,

we need support of longer key length. I need a 72 bytes support

error message with latest fish10: ERROR: key length exceeds limit of 56 bytes.

**Comment by thezoggy** [comment]
per the readme

> To work around keys exceeding a length of 56 bytes, the blow.ini option enforce_max_key_length=0 can be used. This option is present from releases starting with 2017-02-25.
