### ISSUE TITLE
Fish on Mirc v7.59 ERROR!!!

### ISSUE THREAD

**Issue by Shadow322** [flakes/mirc_fish_10#64]
i have updated OpenSSL to 1.1.1d for 32/64 bit still not working

https://i.imgur.com/rLW551B.png

**Comment by silv3rr** [comment]
seems it cannot find ssl lib dll's
make sure you have the libcrypto-1_1.dll  and libssl-1_1.dll in mirc dir
check mirc.ini has:
```
[ssl]
load=1
```
verify in mirc: `//echo ssl: $sslready`
