### ISSUE TITLE
PRIVMSG / CPRIVMSG ?!

### ISSUE THREAD

**Issue by fred0r** [flakes/mirc_fish_10#65]
https://www.mirc.com/versions.txt
```
29/11/2018 - mIRC v7.53

21.Added support for CPRIVMSG and CNOTICE. If listed in numeric 005,
   PRIVMSG and NOTICE will be automatically upgraded for most
   outgoing messages if you are an op/voice on a channel and message
   a user on the same channel.
```
The KeyExchange works fine on both Sides (ECB+CBC) and the mirc_fish10 is able to read encrypted Chat, but it sends uncrypted Text.

When running ZNC with `raw`-Module enabled, it looks like this on the mirc_fish10-side:
```
<*raw> IRC -> [:fred!fred@host PRIVMSG JOHN_DOE :+OK *JeqX+JEKjlUFweuYkx7ojA==]
<*raw> YOU -> [CPRIVMSG fred #chan :man müßte mal gucken was PRIVMSG vs CPRIVMSG is]
```
`JOHN_DOE` and me had a lot channels in common and it seems to only happen on voiced/oped users, since i was op and he had voice on `#chan`
After removing `JOHN_DOE`s voice on `#chan`, query was instantly encrypted on both sides.

**Comment by fred0r** [comment]
All the upper is tested on EFnet.
Some ppl report, that this doesnt happen on Linknet or on a private Unrealircd-Server.

**Comment by silv3rr** [comment]
Quick & dirty workaround:

Add to top of fish_10.mrc (before `on *:START`)

```
on *:PARSELINE:out:CPRIVMSG *:{
  noop $regsubex(pl,$parseline, /^CPRIVMSG ([^ ]+) #[^ ]+ (:[^ ]+)/,PRIVMSG \1 \2, &pl)
  if ($bvar(&pl,0) > 14) {
    .parseline -ob &pl
  }
  unset &pl
}
```

This will just always replace CPRIVMSG by PRIVMSG before the command gets send to server.

LinkNet, Unreal and ngIRCd &c do not support CPRIVMSG  so it's not an issue there.
Sending VERSION command to sever can be used to check for support.

**Comment by silv3rr** [comment]
Oh and ofcourse the permanent solution would be adding CPRIVMSG to _OnOutgoingIRCLine function in fish-main.cpp

https://github.com/flakes/mirc_fish_10/blob/8b61aaf4dbea5ae5825f1e56dc03cca6bebbd716/fish_10/src/fish-main.cpp#L433
and lines below

**Comment by fred0r** [comment]
@silv3rr Nice - can you please create a Pull Request for the Perm-Fix?

**Comment by zc0nf** [comment]
@fred0r @silv3rr 
Hello, is there a way to verify that it only works fine with mIRC after the patch is applied?

Thx! 👍

**Comment by flakes** [comment]
Looks like I fixed this, but forgot to make a release? LOL

**Comment by flakes** [comment]
New version released today, including a fix for this issue, please test, and open a new issue if required 😝
